# Enable mouse scrolling, pane selection, and resizing.
set -g mouse on

# Copy mouse selections to the macOS clipboard on release.
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'
